### ISSUE TITLE
Optim Sensitivity -- Review for ReScience

### ISSUE THREAD

**Issue by juniperlsimonis** [pboesu/replication_candy_1991#6]
I appreciate the acknowledgement of the importance of starting values for the results in optim, but it would be really useful to have 
1. information the range of parameters used 
2. some of those results displayed 
3.  code showing the user how you did that exploration.

Is it possible to include that?

**Comment by pboesu** [comment]
Most of the original discrepancies between parameter estimates could be resolved by adding parameter scaling factors to the optimisation routine. Regardless I retained the initial value sensitivity analysis example added in a9cc8643d35fc89e6e5921d71b5e2a11555b82e9 , b1df113459f834b71fc94bbec14abaa8c3cf5625
