### ISSUE TITLE
Figures -- Review for ReScience

### ISSUE THREAD

**Issue by juniperlsimonis** [pboesu/replication_candy_1991#7]
Nice job with the figures!

A few quick notes:

you're saving them out as Fig 2 and Fig 3 but using them as Fig 1 and Fig 2 --- suggest aligning

note on them or in the legend what specific replication you're matching, as you show multiple model fits for these.

**Comment by pboesu** [comment]
https://github.com/pboesu/replication_candy_1991/commit/92dec06d96024669aa18e54578b3848b749da325 - clarifies the figure naming in the code and file names as well as the replication implementation underlying the figures. These are figures 1 and 2 in the replication manuscript, but figures 2 and 3, respectively in the source manuscript.
