### ISSUE TITLE
Manuscript Text -- Review for ReScience

### ISSUE THREAD

**Issue by juniperlsimonis** [pboesu/replication_candy_1991#8]
I think the text of the MS flows nicely and is generally easy to read.

A few quick additional notes/questions 

- Include the specific optimization routines being used in the model fits. Optim has multiple options. If you used the default, make sure to include that.
- Similarly, with all of the functions, tell us more of the arguments you used/any decisions around that. Especially in the context of the minor differences you found, what did you explore and how?
- Contextualize the degree of parameter difference you mention on line 129: relatively speaking, what does this discrepancy mean?

**Comment by pboesu** [comment]
Revisions checklist

- [x] add details of `optim` method  - adressed in e99ba55
- [x] broader context for other function arguments - added statements that default settings were used in all fittting functions other than `optim`
- [x] quantify parameter differences between original and replication - adressed in 644ab1438ea7413decc6dbdddd3882d3c5e51686
